### ISSUE TITLE
Cant Launch Bot From start.py, 'module' object is not callable

### ISSUE THREAD

**Issue by DudeDaCode** [The-Codin-Hole/HotWired-Bot#106]
[`start.py`](https://github.com/The-Codin-Hole/HotWired-Bot/blob/f2be6e60742bcb387e80fe40131fc8d0a5f8216a/start.py) file doesn't start the bot properly and raises an exception:
```
Traceback (most recent call last):
  File "G:\New Downloads\HotWired-Bot\start.py", line 5, in <module>
    main()
TypeError: 'module' object is not callable
```

**Comment by ItsDrike** [comment]
We are aware of this issue, the `start.py` file is a remnant of an old start system and it will be removed soon, the bot should be started with `pipenv run start` or directly by `py -m bot`, but with the direct approach you'll need to be in the pipenv enviroment (`pipenv shell`)
