### ISSUE TITLE
Possible exposed key

### ISSUE THREAD

**Issue by ItsDrike** [The-Codin-Hole/HotWired-Bot#3]
I was looking through [`utils/wolframscrape.py`](https://github.com/janaSunrise/HotWired-Bot/blob/7b3ee4a08d282116b9a958900b7cf298c4cce99a/utils/wolframscrape.py) and found this:

https://github.com/janaSunrise/HotWired-Bot/blob/7b3ee4a08d282116b9a958900b7cf298c4cce99a/utils/wolframscrape.py#L3

This might be exposed API key to WolframAlpha, if that is the case, this needs to be removed, the API key needs to be reset and accepted through environmental variables stored in `.env`

**Comment by janaSunrise** [comment]
It's Solved
