### ISSUE TITLE
As a moderator, i Need to be DM certain Users or everyone in a Server

### ISSUE THREAD

**Issue by janaSunrise** [The-Codin-Hole/HotWired-Bot#55]
Commands
-----------
`dm <list of users> <message>` : This DMs all the specified users with given message

`dmall <message>` : This DMs all the users in my server with The given Message

Permissions required for this : Since it's only for moderators, the permissions can be `kick_members=True` or `ban_members=True`

**Comment by ItsDrike** [comment]
Permissions for something like this has to be `Administrator` only, a command like `dmall` would be an amazing way to spam ads, etc to users, it is absolutely mandatory that this is only allowed to Administrators and noone else
