### ISSUE TITLE
`Commands` is a very undescriptive name for cog

### ISSUE THREAD

**Issue by ItsDrike** [The-Codin-Hole/HotWired-Bot#7]
Cog [`commands.py`](https://github.com/janaSunrise/HotWired-Bot/blob/7b3ee4a08d282116b9a958900b7cf298c4cce99a/cogs/commands.py) shouldn't be named `Commands` as that name doesn't mean anything, basically, all cogs have some commands in them, the cog should be renamed to something more meaningful.

If the cog can't be renamed as is because it's not doing anything specific, it should be split into smaller, more specific cogs, for example `information` cog

**Comment by Theodore-Robinson** [comment]
I will solve this. Lets not discuss issues with our code on github, we'll handle it on discord
I'm closing this issue for the same reason I closed [this repo](https://github.com/The-Codin-Hole/HotWired-Bot/issues/9#issuecomment-642409018)
